### ISSUE TITLE
Touch Controls

### ISSUE THREAD

**Issue by metafaniel** [FdelMazo/celeste-feather-game#1]
Hi. I tried to play this game on a mobile device, but it seems it has no touch controls. One can only use click or space bar key but It'd be nice to be able to play it using touch controls (I was in need to calm down and I couldn't because of this at that moment haha).
Thanks and greetings.

**Comment by FdelMazo** [comment]
Will take a look later this week!

**Comment by FdelMazo** [comment]
Hey @metafaniel , I just deployed a working touch version to the site. It's been a while since I touched this code, so let me know if it works for you before closing the issue!

**Comment by metafaniel** [comment]
It works! I've tested it using Vivaldi, Chrome and even Safari. Thanks.
The sound can't be enabled evidently, but that's a different issue.

**Comment by FdelMazo** [comment]
great! Yeah, I couldn't find an easy way to turn on the sound without a large refactor and wanted to have the touch controls as soon as possible.

Lets just say that if it's on mobile the user can probably have a app play music on the background and call it a day? :smile:

**Comment by metafaniel** [comment]
This app, being conceived as a way to reduce anxiety and not being able to use it on a mobile device, was a major issue, but the sound is not as vital so I think is fair enough haha. Thanks for your effort to recreate this mini-game.
